In [2]:
from icecube import icetray, dataio, dataclasses, simclasses, clsim
from icecube.icetray import I3Units, OMKey, I3Frame
from I3Tray import *
from icecube.dataclasses import ModuleKey
import numpy as np
from scipy import stats
from iminuit import minimize
from likelihoodHelpers import log_likelihood_biGauss, log_likelihood_doublePeak
from likelihoodHelpers import likelihood_ratio_doublePeak, likelihood_ratio_biGauss, biGauss, double_peak
import scipy, csv
import curveFit

In [ ]:
'''
Loading Geometry
'''

gcd_file = '/home/users/akatil/P-ONE/GCD_files/PONE_Phase1.i3.gz'
gcd = dataio.I3File(gcd_file)
cframe = gcd.pop_frame()
geometry = cframe["I3Geometry"]
omgeo = geometry.omgeo
print('loaded geometry')

infile = '/data/p-one/akatil/step_5_medium_water/NuTau_NuE_20Events/step_5_98_medium_water_custom_mDOM_recoPulse.i3.gz'

tray = I3Tray()

tray.AddModule('I3Reader', 'reader',
            FilenameList = [gcd_file, infile]
            )

tray.AddModule(curveFit.curveFit, "Double Peak Selector",
               omgeo = omgeo,
               InputMCPETree = "I3RecoPulses",
               OutputMCPETree = "Parameters",
               FrameList = [4],
               StringList = [7],
               DOMList = [6])

tray.AddModule("TrashCan","adios")
tray.Execute()
tray.Finish()

loaded geometry
Now Histogramming
Now Histogramming
('Frame number - 4', 'String number - 7', 'DOM number - 6')
Now Histogramming
*****************One Peak*****************
(array([-3.19744231e-13,  5.00000000e+01,  5.00000000e+00,  1.90000000e+01]), 2140.6967525417067)
*****************One Peak*****************
(array([2.25976575e-02, 5.00000000e+01, 5.00000000e+00, 1.90000000e+01]), 2136.8841656996187)
*****************One Peak*****************
(array([-2.25985749e-02,  5.00000000e+01,  5.00000000e+00,  1.90000000e+01]), 2144.514800230693)
*****************One Peak*****************
(array([9.77242778e-03, 5.00000000e+01, 5.00000000e+00, 1.90000000e+01]), 2139.047336594889)
*****************One Peak*****************
(array([-9.77259935e-03,  5.00000000e+01,  5.00000000e+00,  1.90000000e+01]), 2142.3471897286117)
*****************One Peak*****************
(array([-3.19744231e-13,  5.00225987e+01,  5.00000000e+00,  1.90000000e+01]), 2138.2330581990363)
*****************One Peak*********

*****************One Peak*****************
(array([ -0.15104202, 113.9987321 ,   1.26318519,  14.3261821 ]), -312.51235866800266)
*****************One Peak*****************
(array([ -0.15104202, 113.9987321 ,   1.26429272,  14.31583629]), -312.5124350706588)
*****************One Peak*****************
(array([ -0.15104202, 113.9987321 ,   1.26429272,  14.33652828]), -312.5121636468817)
*****************One Peak*****************
(array([ -0.16237146, 113.9994287 ,   1.26286502,  14.31401131]), -312.5125698679759)
*****************One Peak*****************
(array([ -0.16160491, 113.99939021,   1.2629616 ,  14.31483476]), -312.5125709323092)
*****************One Peak*****************
(array([ -0.14323117, 113.99939021,   1.2629616 ,  14.31483476]), -312.51291327709845)
*****************One Peak*****************
(array([ -0.17997924, 113.99939021,   1.2629616 ,  14.31483476]), -312.51207910987085)
*****************One Peak*****************
(array([ -0.16160491, 113.99982002,   1.2629616 ,  

*****************Double Peak*****************
(array([-4.08621325e+01,  2.00000000e+01,  1.00000000e+00,  1.89999828e+01,
       -3.09974268e-13,  1.99943583e+01,  1.00000000e+00,  1.89999828e+01]), 1570.6325210436783)
*****************Double Peak*****************
(array([-4.08621325e+01,  2.00000000e+01,  1.00000000e+00,  1.89999828e+01,
       -3.09974268e-13,  2.00000000e+01,  1.00061409e+00,  1.89999828e+01]), 1570.4264193905406)
*****************Double Peak*****************
(array([-4.08621325e+01,  2.00000000e+01,  1.00000000e+00,  1.89999828e+01,
       -3.09974268e-13,  2.00000000e+01,  9.99386077e-01,  1.89999828e+01]), 1568.5358777126803)
*****************Double Peak*****************
(array([-4.08621325e+01,  2.00000000e+01,  1.00000000e+00,  1.89999828e+01,
       -3.09974268e-13,  2.00000000e+01,  1.00000000e+00,  1.89999932e+01]), 1569.4807009649849)
*****************Double Peak*****************
(array([-4.08621325e+01,  2.00000000e+01,  1.00000000e+00,  1.89999828e+01,
  

*****************Double Peak*****************
(array([-40.45179313,  96.52414567,   0.21308033,  18.99998453,
         8.18571029,  22.1240364 ,   0.81200226,  18.99999019]), -245.60644820491896)
*****************Double Peak*****************
(array([-40.45179313,  96.52414567,   0.21308033,  18.99998453,
         8.18571029,  22.1240364 ,   0.8148132 ,  18.99998667]), -245.6114689549693)
*****************Double Peak*****************
(array([-40.45179313,  96.52414567,   0.21308033,  18.99998453,
         8.18571029,  22.1240364 ,   0.8148132 ,  18.99990167]), -245.6115793340025)
*****************Double Peak*****************
(array([-39.92324679,  99.74429716,   0.1978044 ,  18.95895389,
         7.95159589,  22.12084861,   0.81606166,  18.99998596]), -250.7448138677827)
*****************Double Peak*****************
(array([-39.25312725, 103.39990306,   0.17931455,  18.7950425 ,
         7.6579218 ,  22.11682431,   0.81763907,  18.99997955]), -253.4436366006789)
*****************Double 

*****************Double Peak*****************
(array([-32.82895426, 113.88190635,   0.27044042,  13.33240335,
         3.35271937,  21.97724465,   0.83326458,  18.99947695]), -288.81003261296036)
*****************Double Peak*****************
(array([-32.64721658, 113.88023306,   0.28047809,  13.56089105,
         3.08549336,  21.97260121,   0.83375237,  18.99941231]), -289.0886608902996)
*****************Double Peak*****************
(array([-32.52169222, 113.87907009,   0.28751702,  13.71719639,
         2.90270018,  21.96939319,   0.83408947,  18.99936545]), -289.16174807214645)
*****************Double Peak*****************
(array([-32.50906393, 113.87907009,   0.28751702,  13.71719639,
         2.90270018,  21.96939319,   0.83408947,  18.99936545]), -289.152687372745)
*****************Double Peak*****************
(array([-32.53432088, 113.87907009,   0.28751702,  13.71719639,
         2.90270018,  21.96939319,   0.83408947,  18.99936545]), -289.1707293702791)
*****************Double 

*****************Double Peak*****************
(array([-32.14734273, 113.98411281,   0.31728968,  11.38537799,
        -1.79086492,  22.06487282,   0.84023168,  18.99504682]), -297.68444094321086)
*****************Double Peak*****************
(array([-32.14734273, 113.98411281,   0.31728968,  11.38537799,
        -1.79086492,  22.06487282,   0.84023168,  18.99194888]), -297.68682067793696)
*****************Double Peak*****************
(array([-32.2833989 , 113.99465517,   0.31025599,  11.35821562,
        -1.67515481,  22.06264375,   0.83941929,  18.99230299]), -297.72974193932436)
*****************Double Peak*****************
(array([-32.3295619 , 113.99695833,   0.30788742,  11.34899895,
        -1.63557742,  22.06188764,   0.8391438 ,  18.99183916]), -297.73255255052675)
*****************Double Peak*****************
(array([-32.31192134, 113.99695833,   0.30788742,  11.34899895,
        -1.63557742,  22.06188764,   0.8391438 ,  18.99183916]), -297.7288888446452)
*****************Doub

*****************Double Peak*****************
(array([-39.76962454, 113.996332  ,   0.19453489,  11.29900194,
        -1.93192815,  21.87003765,   0.80191042,  18.32359462]), -298.7386295944679)
*****************Double Peak*****************
(array([-39.76962454, 113.996332  ,   0.19453489,  11.30867037,
        -1.91707033,  21.87003765,   0.80191042,  18.32359462]), -298.739623853588)
*****************Double Peak*****************
(array([-39.76962454, 113.996332  ,   0.19453489,  11.30867037,
        -1.94676095,  21.87003765,   0.80191042,  18.32359462]), -298.7368961082044)
*****************Double Peak*****************
(array([-39.76962454, 113.996332  ,   0.19453489,  11.30867037,
        -1.93192815,  21.94196669,   0.80191042,  18.32359462]), -298.75225948795077)
*****************Double Peak*****************
(array([-39.76962454, 113.996332  ,   0.19453489,  11.30867037,
        -1.93192815,  21.7981987 ,   0.80191042,  18.32359462]), -298.7242455470574)
*****************Double P

*****************Double Peak*****************
(array([-36.87385615, 113.98850242,   0.23166604,  11.94089044,
        -1.6133984 ,  22.31546391,   0.78433123,  12.88904563]), -300.6433852935785)
*****************Double Peak*****************
(array([-36.87385615, 113.98850242,   0.23166604,  11.94089044,
        -1.6133984 ,  22.11462235,   0.78433123,  12.88904563]), -300.58346973676896)
*****************Double Peak*****************
(array([-36.87385615, 113.98850242,   0.23166604,  11.94089044,
        -1.6133984 ,  22.21495711,   0.78957216,  12.88904563]), -300.6088204225083)
*****************Double Peak*****************
(array([-36.87385615, 113.98850242,   0.23166604,  11.94089044,
        -1.6133984 ,  22.21495711,   0.77910627,  12.88904563]), -300.6180327307235)
*****************Double Peak*****************
(array([-36.87385615, 113.98850242,   0.23166604,  11.94089044,
        -1.6133984 ,  22.21495711,   0.78433123,  12.91761427]), -300.61253842565225)
*****************Double

*****************Double Peak*****************
(array([-11.78801216, 113.98660837,   0.78083185,  13.06734439,
        -1.12251267,  24.73580159,   0.81083996,   5.75999085]), -309.9336910989136)
*****************Double Peak*****************
(array([-11.78801216, 113.98660837,   0.78083185,  13.04681256,
        -1.12251267,  24.73580159,   0.81083996,   5.75999085]), -309.93417284075093)
*****************Double Peak*****************
(array([-11.78801216, 113.98660837,   0.78083185,  13.05708072,
        -1.09329602,  24.73580159,   0.81083996,   5.75999085]), -309.9304057606947)
*****************Double Peak*****************
(array([-11.78801216, 113.98660837,   0.78083185,  13.05708072,
        -1.15165018,  24.73580159,   0.81083996,   5.75999085]), -309.93745466656134)
*****************Double Peak*****************
(array([-11.78801216, 113.98660837,   0.78083185,  13.05708072,
        -1.12251267,  24.93204309,   0.81083996,   5.75999085]), -309.9269658083979)
*****************Double

*****************Double Peak*****************
(array([ -6.4467473 , 113.89542852,   1.01928818,  13.43002508,
         0.20740402,  16.34539839,   2.04784221,   6.19308108]), -312.6375667210359)
*****************Double Peak*****************
(array([-6.54654429e+00,  1.13926717e+02,  1.01379415e+00,  1.34465070e+01,
       -7.89492428e-02,  1.61701360e+01,  1.85909453e+00,  6.21699811e+00]), -312.63326211923487)
*****************Double Peak*****************
(array([ -6.43844479, 113.89542852,   1.01928818,  13.43002508,
         0.20740402,  16.34539839,   2.04784221,   6.19308108]), -312.6444773882069)
*****************Double Peak*****************
(array([ -6.45512707, 113.89542852,   1.01928818,  13.43002508,
         0.20740402,  16.34539839,   2.04784221,   6.19308108]), -312.6305632404605)
*****************Double Peak*****************
(array([ -6.4467473 , 113.88883911,   1.01928818,  13.43002508,
         0.20740402,  16.34539839,   2.04784221,   6.19308108]), -312.63255686610694)

         0.43404392,  16.27004117,   2.21245082,   6.2281735 ]), -313.1342837311415)
*****************Double Peak*****************
(array([ -6.02538315, 113.99896039,   0.99165517,  13.46338852,
         0.43404392,  16.12208871,   2.21245082,   6.2281735 ]), -313.1321228895543)
*****************Double Peak*****************
(array([ -6.02538315, 113.99896039,   0.99165517,  13.46338852,
         0.43404392,  16.19599446,   2.23350312,   6.2281735 ]), -313.1326624501939)
*****************Double Peak*****************
(array([ -6.02538315, 113.99896039,   0.99165517,  13.46338852,
         0.43404392,  16.19599446,   2.19146997,   6.2281735 ]), -313.13375733346913)
*****************Double Peak*****************
(array([ -6.02538315, 113.99896039,   0.99165517,  13.46338852,
         0.43404392,  16.19599446,   2.21245082,   6.26458273]), -313.1335325837302)
*****************Double Peak*****************
(array([ -6.02538315, 113.99896039,   0.99165517,  13.46338852,
         0.43404392,  16

        -0.15140772,  17.06821334,   1.65849898,   6.14847378]), -313.1600570413496)
*****************Double Peak*****************
(array([ -6.00020648, 113.99999994,   0.98580667,  13.3823212 ,
        -0.15140772,  17.06821334,   1.65849898,   6.14847378]), -313.1606348746821)
*****************Double Peak*****************
(array([ -6.00080933, 113.99990504,   0.98580667,  13.3823212 ,
        -0.15140772,  17.06821334,   1.65849898,   6.14847378]), -313.1603463101134)
*****************Double Peak*****************
(array([ -6.00080933, 113.99989536,   0.98580667,  13.3823212 ,
        -0.15140772,  17.06821334,   1.65849898,   6.14847378]), -313.16033904169024)
*****************Double Peak*****************
(array([ -6.00080933, 113.99999994,   0.98665684,  13.3823212 ,
        -0.15140772,  17.06821334,   1.65849898,   6.14847378]), -313.1606123687052)
*****************Double Peak*****************
(array([ -6.00080933, 113.99999994,   0.98495683,  13.3823212 ,
        -0.15140772,  17

*****************Double Peak*****************
(array([ -6.00007656, 113.99999838,   0.98718214,  13.37142116,
        -1.27391945,  16.62474974,   1.22780785,   6.34174105]), -313.18008301033393)
*****************Double Peak*****************
(array([ -6.00007656, 113.99999838,   0.98718214,  13.37142116,
        -1.27391945,  16.6985707 ,   1.23840732,   6.34174105]), -313.1800631256826)
*****************Double Peak*****************
(array([ -6.00007656, 113.99999838,   0.98718214,  13.37142116,
        -1.27391945,  16.6985707 ,   1.21724759,   6.34174105]), -313.18006911838194)
*****************Double Peak*****************
(array([ -6.00007656, 113.99999838,   0.98718214,  13.37142116,
        -1.27391945,  16.6985707 ,   1.22780785,   6.37792033]), -313.1800364398121)
*****************Double Peak*****************
(array([ -6.00007656, 113.99999838,   0.98718214,  13.37142116,
        -1.27391945,  16.6985707 ,   1.22780785,   6.30563244]), -313.1800894415893)
*****************Double

Now Histogramming
Now Histogramming
Now Histogramming
Now Histogramming


In [ ]:
'''
        # Check if I want to debug this frame
        debug_mode = False
        if len(self.debug) > 0:
            if self.debug[0] == 'all':
                debug_mode = True
            if self.frame_counter in self.debug:
                debug_mode = True
                print('Debugging frame ', self.frame_counter)
        # Increase the frame counter

        '''